feat: add crawling
TayMcKenzieNZ/rpemotes pull request #114
Opened 2023-01-21 19:35 UTC by MadsLeander

This is just a draft, I'll work on it more later today/tomorrow. If you find any issues/have any ideas feel free to make a comment about them.

As of now, crawling includes:
- Crawling backwards and forwards
- Smoothly going left/right if crawling
- Animated moving left/right if laying still (to force a sync, won't sync heading otherwise)
- Animated intro, both normal and diving (no animation when going from crouching)
- Animated outro to both standing up and to crouching

2023-01-21 19:37 UTC, MadsLeander commented
Here is also a small video for those who are too lazy to test the code themselves: https://www.youtube.com/watch?v=rIG8HoqGnaY&ab_channel=MadsNaustdal

2023-01-22 01:16 UTC, iSentrie commented
wow! :) have you tried double click `X` and see if it instantly stands up?

2023-01-22 03:00 UTC, iSentrie requested changes

2023-01-22 14:28 UTC, MadsLeander commented on client/Crouch.lua
> +local isProne = false
Thanks for the suggestion!

2023-01-22 22:40 UTC, iSentrie commented on client/Crouch.lua
>          EmoteChatMessage("You can't crouch right now.")
this and other chat messages should be removed once WIP is done, might be annoying while driving or doing your things and chat messages pops up even if you dont try to crouch or prone

2023-01-22 23:02 UTC, MadsLeander commented on client/Crouch.lua
>          EmoteChatMessage("You can't crouch right now.")
True enough, my only concern I have about removing them is that players will be confused as to why it isn't working, but again, most of the situations should be self-explanatory. I'll give it some thought until tomorrow.

2023-01-22 23:09 UTC, MadsLeander commented on client/Crouch.lua
>          EmoteChatMessage("You can't crouch right now.")
"I'll give it some thought until tomorrow" did not age well, I'm already now I'm starting to agree with you after some testing and adjusting.

2023-01-23 14:37 UTC, iSentrie commented
double tap `rcontrol`

https://user-images.githubusercontent.com/29688478/214066576-a7149327-0d86-4ddc-b538-542bc3da9a93.mp4

2023-01-23 15:17 UTC, MadsLeander commented
Added some checks, which should fix most of the double-tap issues, but it still needs some more testing to ensure that all cases are covered.

2023-01-23 16:56 UTC, MadsLeander commented
I'll mark this as ready for review. I don't think there should be any more issues.

2023-01-23 19:49 UTC, iSentrie requested changes
only 1 issue, that script allow to crawl with props attached, potential solution provided

and 1 thing to discuss, so we have a control for canceling animations `X` by default, maybe if that would cancel crawling it would be comfortable for some (we don't need this for crouching, but for crawling, probably a good idea?)

2023-01-23 19:49 UTC, iSentrie commented on client/Crouch.lua
> +
we probably don't want to crawl with props attached, so this might be a solution
```suggestion
EmoteCancel()
```

2023-01-23 19:59 UTC, iSentrie requested changes
just for cleanliness, we dont need these args

2023-01-23 19:59 UTC, iSentrie commented on client/Crouch.lua
> +        RegisterCommand('-crouch', function(source, args, raw) end, false) -- This needs to be here to prevent errors/warnings
we don't needs these, wont be used
```suggestion
        RegisterCommand('+crouch', function() CrouchKeyPressed() end, false)
        RegisterCommand('-crouch', function() end, false) -- This needs to be here to prevent errors/warnings
```

2023-01-23 19:59 UTC, iSentrie commented on client/Crouch.lua
> +    RegisterCommand('crouch', function(source, args, raw)
```suggestion
    RegisterCommand('crouch', function()
```

2023-01-23 19:59 UTC, iSentrie commented on client/Crouch.lua
> +    RegisterCommand('crawl', function(source, args, raw) CrawlKeyPressed() end, false)
just for cleanliness
```suggestion
    RegisterCommand('crawl', function() CrawlKeyPressed() end, false)
```

2023-01-23 20:25 UTC, MadsLeander commented on client/Crouch.lua
> +    RegisterCommand('crouch', function(source, args, raw)
Made a separate commit with all of them in one.

2023-01-23 22:27 UTC, TayMcKenzieNZ commented
You guys are legends 😎

2023-01-23 22:44 UTC, merged